{"status_code":15,"lang":"python3","run_success":false,"runtime_error":"Line 38: TypeError: None is not valid value for the expected return type integer","full_runtime_error":"TypeError: None is not valid value for the expected return type integer\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    raise TypeError(str(ret) + \" is not valid value for the expected return type integer\");\nLine 38 in _driver (Solution.py)\n    _driver()\nLine 45 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: '<' not supported between instances of 'int' and 'NoneType'\nLine 14 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    out = ser._serialize(ret, 'integer')\nLine 36 in _driver (Solution.py)","status_runtime":"N/A","memory":17256000,"question_id":"1713","elapsed_time":53,"compare_result":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","code_output":"","std_output":"","last_testcase":"[1,0,0,2,3]\n[0,3,0,4,0]","expected_output":"8","task_finish_time":1733713924174,"task_name":"judger.judgetask.Judge","finished":true,"total_correct":0,"total_testcases":99,"runtime_percentile":null,"status_memory":"N/A","memory_percentile":null,"pretty_lang":"Python3","submission_id":"1473954557","status_msg":"Runtime Error","state":"SUCCESS"}